//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.12 at 07:50:59 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datetime.ru/timestamp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.clientsoap.wsdl;
